const listingList = [
    {
        id: 1,
        img: "https://productimages.hepsiburada.net/s/32/375/10354042765362.jpg",
        title: "Apple iPad Pro ",
        price: "4000",
        category: "ELECTRONICS",
        location: "Istanbul",
        listingDate: "2022-04-01",
        description:
            "Apple iPad Pro - 12.9-inch - Wi-Fi - 64GB - Space Gray, minor scratches",
        condition: "Used-Good Condition",
    },
    {
        id: 2,
        img: "https://pyxis.nymag.com/v1/imgs/86c/882/b47a32d8e72df7aeadf74490a82aaa9432.rsquare.w600.jpg",
        title: "Leather Couch",
        price: "1000",
        category: "FURNITURE",
        location: "Izmir",
        listingDate: "2022-07-01",
        description: "Leather Couch - Brown, doesn't have stains",
        condition: "Used-Mint Condition",
    },
    {
        id: 3,
        img: "https://productimages.hepsiburada.net/s/32/375/10354042765362.jpg",
        title: "Apple iPad Pro ",
        price: "4000",
        category: "ELECTRONICS",
        location: "Istanbul",
        listingDate: "2022-04-01",
        description:
            "Apple iPad Pro - 12.9-inch - Wi-Fi - 64GB - Space Gray, minor scratches",
        condition: "Used-Good Condition",
    },
    {
        id: 4,
        img: "https://pyxis.nymag.com/v1/imgs/86c/882/b47a32d8e72df7aeadf74490a82aaa9432.rsquare.w600.jpg",
        title: "Leather Couch",
        price: "1000",
        category: "FURNITURE",
        location: "Izmir",
        listingDate: "2022-07-01",
        description: "Leather Couch - Brown, doesn't have stains",
        condition: "Used-Mint Condition",
    },
    {
        id: 5,
        img: "https://productimages.hepsiburada.net/s/32/375/10354042765362.jpg",
        title: "Apple iPad Pro ",
        price: "4000",
        category: "ELECTRONICS",
        location: "Istanbul",
        listingDate: "2022-04-01",
        description:
            "Apple iPad Pro - 12.9-inch - Wi-Fi - 64GB - Space Gray, minor scratches",
        condition: "Used-Good Condition",
    },
    {
        id: 6,
        img: "https://pyxis.nymag.com/v1/imgs/86c/882/b47a32d8e72df7aeadf74490a82aaa9432.rsquare.w600.jpg",
        title: "Leather Couch",
        price: "1000",
        category: "FURNITURE",
        location: "Izmir",
        listingDate: "2022-07-01",
        description: "Leather Couch - Brown, doesn't have stains",
        condition: "Used-Mint Condition",
    },
    {
        id: 7,
        img: "https://productimages.hepsiburada.net/s/32/375/10354042765362.jpg",
        title: "Apple iPad Pro ",
        price: "4000",
        category: "ELECTRONICS",
        location: "Istanbul",
        listingDate: "2022-04-01",
        description:
            "Apple iPad Pro - 12.9-inch - Wi-Fi - 64GB - Space Gray, minor scratches",
        condition: "Used-Good Condition",
    },
    {
        id: 8,
        img: "https://pyxis.nymag.com/v1/imgs/86c/882/b47a32d8e72df7aeadf74490a82aaa9432.rsquare.w600.jpg",
        title: "Leather Couch",
        price: "1000",
        category: "FURNITURE",
        location: "Izmir",
        listingDate: "2022-07-01",
        description: "Leather Couch - Brown, doesn't have stains",
        condition: "Used-Mint Condition",
    },
    {
        id: 9,
        img: "https://productimages.hepsiburada.net/s/32/375/10354042765362.jpg",
        title: "Apple iPad Pro ",
        price: "4000",
        category: "ELECTRONICS",
        location: "Istanbul",
        listingDate: "2022-04-01",
        description:
            "Apple iPad Pro - 12.9-inch - Wi-Fi - 64GB - Space Gray, minor scratches",
        condition: "Used-Good Condition",
    },
    {
        id: 10,
        img: "https://pyxis.nymag.com/v1/imgs/86c/882/b47a32d8e72df7aeadf74490a82aaa9432.rsquare.w600.jpg",
        title: "Leather Couch",
        price: "1000",
        category: "FURNITURE",
        location: "Izmir",
        listingDate: "2022-07-01",
        description: "Leather Couch - Brown, doesn't have stains",
        condition: "Used-Mint Condition",
    },
];

export default listingList;
